# Generated by Django 5.0.6 on 2025-07-07 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pokedex_id', models.PositiveIntegerField(unique=True)),
                ('height', models.PositiveIntegerField(help_text='Výška v decimetrech')),
                ('weight', models.PositiveIntegerField(help_text='Váha v hectogramech')),
                ('base_experience', models.PositiveIntegerField(default=0)),
                ('sprite_url', models.URLField(blank=True, null=True)),
                ('hp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('attack', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('defense', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('special_attack', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('special_defense', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('speed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_legendary', models.BooleanField(default=False)),
                ('is_mythical', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémoni',
                'ordering': ['pokedex_id'],
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Pokémon typ',
                'verbose_name_plural': 'Pokémon typy',
            },
        ),
        migrations.CreateModel(
            name='BattleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Výhra'), ('lose', 'Prohra'), ('draw', 'Remíza')], max_length=10)),
                ('battle_log', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu_team', models.ManyToManyField(related_name='cpu_battles', to='Main.pokemon')),
                ('user_team', models.ManyToManyField(related_name='user_battles', to='Main.pokemon')),
            ],
            options={
                'verbose_name': 'Historie bitvy',
                'verbose_name_plural': 'Historie bitev',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon', to='Main.pokemontype'),
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('from_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_to', to='Main.pokemon')),
                ('to_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_from', to='Main.pokemon')),
            ],
            options={
                'verbose_name': 'Evoluce',
                'verbose_name_plural': 'Evoluce',
                'unique_together': {('from_pokemon', 'to_pokemon')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.pokemon')),
            ],
            options={
                'verbose_name': 'Oblíbený Pokémon',
                'verbose_name_plural': 'Oblíbení Pokémoni',
                'unique_together': {('session_key', 'pokemon')},
            },
        ),
    ]
